### ISSUE TITLE
Code contains Wacatac.B!ml VIRUS

### ISSUE THREAD

**Issue by PwrSrg** [Duartemartins/flowbite_jekyll#1]
I downloaded your repo and Windows Defender instantly flagged it as containing the **Wacatac.B!ml VIRUS**.

Trojan: **Script/Wacatac.B!ml**
Alert level: **Severe**
Status: **Active**
Category: **Trojan**

![image](https://github.com/Duartemartins/flowbite_jekyll/assets/711603/a823ba52-1ce2-4a2a-831e-bde3d9fc7172)

**Comment by bit-of-a-shambles** [comment]
That's probably a false positive. Can you narrow down which file is flagging it? I also don't use Windows.

**Comment by PwrSrg** [comment]
Yep, I was hoping that was the case.  It had flagged the **postcss.config.js** file, but it looks totally fine.  I just downloaded it again and it didn't flag it at all.  I even scanned it and it said it was fine.  I definitely thought it was strange, especially in simple development files, but had never run into that before.
